---
title: "Project 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggcorrplot)
```

#Basic RSA (1-3)
```{r}
# Read data and create 12 subject with added noise
NeuralResponses <- read.table('NeuralResponses')
set.seed(100)
for (i  in 1:12) {
  nam <- paste("subject", i, sep = "")
  assign(nam, rnorm(9200, 0, 1)+ NeuralResponses)
}

```


```{r}
# RDM for the original NeuralResponses
NeuralResponses %>%
  t() %>%
  cor(method = 'pearson') %>% 
  as.data.frame() %>% 
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("RDM of Original Neural Responses")


# RDM for subjects
subject1 %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("RDM of Subject1")

subject2 %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("RDM of Subject2")

subject3 %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("RDM of Subject3")

subject4 %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("RDM of Subject4")

#### ----- ####

```
```{r}
meanMatrix = (subject1 + subject2 + subject3 + subject4 + subject5+ subject6+
                subject7 + subject8 + subject9 + subject10 + subject11 + subject12) / 12 
meanMatrix %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("averaged RDM of all subjects")
```

# Hypothesis Testing (4 - 10)
```{r}
# Binary Classification of of the images 
CategoryVectors <- read.table('CategoryVectors')

# Labels of the categories (12 categories)
CategoryLabels <- read.table('CategoryLabels')

# Function that loops through a vector 
# And compares each pair 
loopThruVec <- function(vector) {
  vec <- vector()
  for (x in 1:length(vector)) {
    for (y in 1:length(vector)) {
        if(vector[x] == vector[y]){
          vec <- append(vec, 0)
        }
        else{
          vec <- append(vec, 1)
        }
      }
  }
  return(vec)
}


animacyMatrix <- as.data.frame(matrix(loopThruVec(CategoryVectors$V1),
                nrow = length(CategoryVectors$V1),
                ncol = length(CategoryVectors$V1)))

# Extract the rows 

# Returns pairs of same animacy, does not use the pairs that compare to itself (e.g. pair <0,0> is not returned)
selectSameAnimacy <- function(df, animacy) {
  combinationPairs <- tibble(x,y) # Nog ff kijken hoe ik dit ga opslaan
  for (x in 1:ncol(df)) {
    for (y in 1:nrow(df)) {
      if(df[x,y] == animacy & x != y){
        combinationPairs <- add_row(x,y)
        # print(paste(x,y))
      }
    }
  }
  return(combinationPairs)
  }
selectSameAnimacy(animacyMatrix, 0)

animacyMatrix %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  ggcorrplot() + 
  ggtitle("averaged RDM of all subjects")



## TEST the Animacy Matrix with a smaller vector ####
testVector <- c(0,0,1,1)
testAnimacy <- as.data.frame(matrix(loopThruVec(testVector),
                                    nrow = length(testVector),
                                    ncol = length(testVector)))

```





# Question 11 --> 
```{r}
NeuroRDM <- read.table('NeuroRDM')

### RMS of NeuroRDM and meanMatrix 

NeuroRDM %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("NeuroRDM")

meanMatrix %>%
  t() %>%
  cor(method = 'pearson') %>%
  as.data.frame() %>%
  mutate_all(funs(1-.)) %>%
  ggcorrplot() + 
  ggtitle("averaged RDM of all subjects")

####  Compare two RDMS



```


