---
title: "GroupProj1"
author: "Saif"
date: "13-11-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Import libraries
library(readr)
library(dplyr)
library(ggplot2)
```


## Question 1 
#1a

```{r}
# Load the data

kpData <- read_csv("keyPressDataWithLaneDeviation.csv")
```

```{r}
# Report Mean, Standard Deviation, and Standard Error of the Mean
# for dualSteerFocus and dualDialFocus
dualSteerData <- subset(kpData, partOfExperiment == 'dualSteerFocus' & typingErrorMadeOnTrial == 0 & phoneNrLengthAfterKeyPress ==11)
dualDialData <- subset(kpData, partOfExperiment == 'dualDialFocus' & typingErrorMadeOnTrial == 0 & phoneNrLengthAfterKeyPress ==11)

View(dualSteerData)

# Average time per participant dualSteer
mds <-mean(aggregate(timeRelativeToTrialStart~pp,dualSteerData,mean)$timeRelativeToTrialStart)
# Std dualSteer
sdds <-sd(aggregate(timeRelativeToTrialStart~pp,dualSteerData,mean)$timeRelativeToTrialStart)
# Standard Error dualSteer
seds <-sd(aggregate(timeRelativeToTrialStart~pp,dualSteerData,mean)$timeRelativeToTrialStart) / sqrt(12)



# Average time per participant dualDial
mdd<-mean(aggregate(timeRelativeToTrialStart~pp,dualDialData,mean)$timeRelativeToTrialStart)
# Std dualDial
sddd<-sd(aggregate(timeRelativeToTrialStart~pp,dualDialData,mean)$timeRelativeToTrialStart)
# Standard Error dualDial
sedd<-sd(aggregate(timeRelativeToTrialStart~pp,dualDialData,mean)$timeRelativeToTrialStart)/ sqrt(12)


table <- matrix(c(mds,sdds,seds,mdd,sddd,sedd),ncol =3, byrow=TRUE)
colnames(table) <-c("M", "SD","SE")
rownames(table) <- c("Steering Focus", "Dialing Focus")
table <- as.data.frame(table)
table
div <- function(x){x/1000}
table <- mutate_each(table, funs(div))
table
```

```{r}
# Question 1b
dualSteerData <- subset(kpData, partOfExperiment == 'dualSteerFocus' & typingErrorMadeOnTrial == 0)
dualDialData <- subset(kpData, partOfExperiment == 'dualDialFocus' & typingErrorMadeOnTrial == 0)

# Mean Lateral Deviation Dual Steer
print("dual Steer Lateral Deviation")
mean(aggregate(abs(lanePosition)~pp,dualSteerData,mean)$'abs(lanePosition)')
# Std Lateral Deviation Dual Steer
sd(aggregate(abs(lanePosition)~pp,dualSteerData,mean)$'abs(lanePosition)')
# Standard Error Lateral Deviation Dual Steer
sd(aggregate(abs(lanePosition)~pp,dualSteerData,mean)$'abs(lanePosition)')/ sqrt(12)

# Mean Lateral Deviation Dual Dial
print("dual Dial Lateral Deviation")
mean(aggregate(abs(lanePosition)~pp,dualDialData,mean)$'abs(lanePosition)')
# Std Lateral Deviation Dual Dial
sd(aggregate(abs(lanePosition)~pp,dualDialData,mean)$'abs(lanePosition)')
# Standard Error Lateral Deviation Dual Dial
sd(aggregate(abs(lanePosition)~pp,dualDialData,mean)$'abs(lanePosition)')/ sqrt(12)

```

```{r}
# Question 1C
# Aggregate averages per participant per digit typed and condition --> average across participants
# Take absolute values of lane deviation
# Use phoneNrLengthAfterKeyPress for absolute lane deviation over time 


# Subset data with only Dial and Steer Data, without errors made on trial


tableData %>%
  subset(partOfExperiment =='dualDialFocus') %>%
  aggregate(by = list(.$phoneNrLengthAfterKeyPress),
          FUN= mean)


aggregate(subset(tableData, partOfExperiment == 'dualDialFocus'),
          by = list(.$phoneNrLengthAfterKeyPress),
          FUN= mean)

tableData
# Relevant data for DialData
dialData <- kpData %>% 
  filter(partOfExperiment =="dualDialFocus" & typingErrorMadeOnTrial == 0)%>%
  select(pp, trial, phoneNrLengthAfterKeyPress, timeRelativeToTrialStart,
         lanePosition, partOfExperiment)

dialData

# Relevant data for SteerData
steerData <- kpData %>% 
  filter(partOfExperiment =="dualSteerFocus" & typingErrorMadeOnTrial == 0)%>%
  select(pp, trial, phoneNrLengthAfterKeyPress, timeRelativeToTrialStart,
         lanePosition, partOfExperiment)

steerData

dialData %>%
  group_by(pp, phoneNrLengthAfterKeyPress) %>%
  summarize(mean_time = mean(timeRelativeToTrialStart, na.rm = TRUE)/1000, 
            mean_deviation = mean(abs(lanePosition)))

steerData %>%
  group_by(pp, phoneNrLengthAfterKeyPress) %>%
  summarize(mean_time = mean(timeRelativeToTrialStart, na.rm = TRUE)/1000, 
            mean_deviation = mean(abs(lanePosition)))


##### AGGREGATE FUNCTIE GEKLOOI
averagesPerPP2 <- kpData %>% 
  filter(typingErrorMadeOnTrial == 0, partOfExperiment == "dualDialFocus" |  # Filter relevant data
           partOfExperiment == "dualSteerFocus" )%>%
  select(pp, trial, phoneNrLengthAfterKeyPress, timeRelativeToTrialStart,   # Select relevant cols
         lanePosition, partOfExperiment) %>%
  mutate(lanePosition = abs(lanePosition)) %>%
  aggregate( formula = timeRelativeToTrialStart ~ pp + partOfExperiment + phoneNrLengthAfterKeyPress,
             FUN = mean,
             data = .)

averageAveragesPerPP2 <- averagesPerPP2 %>%
  aggregate(formula = timeRelativeToTrialStart ~ phoneNrLengthAfterKeyPress + partOfExperiment,
            FUN = mean,
            data = .) %>%
  mutate(timeRelativeToTrialStart = timeRelativeToTrialStart / 1000)


averageAveragesPerPP <-


mean(kpData$timeRelativeToTrialStart[kpData$pp ==1 & kpData$partOfExperiment == 'dualSteerFocus'] & kpData$phoneNrLengthBeforeKeyPress == 5)
##### AGGREGATE FUNCTIE GEKLOOI
```



```{r}
## 1C
############# === Da Real Shit === ###########


# Subset averages per participant  
averagesPerPP <- kpData %>% 
  filter(typingErrorMadeOnTrial == 0, partOfExperiment == "dualDialFocus" |  # Filter relevant data
           partOfExperiment == "dualSteerFocus" )%>%
  select(pp, trial, phoneNrLengthAfterKeyPress, timeRelativeToTrialStart,   # Select relevant cols
         lanePosition, partOfExperiment) %>%
  group_by(pp, phoneNrLengthAfterKeyPress, partOfExperiment) %>%            # Group by by relevant cols
  summarize(mean_time = mean(timeRelativeToTrialStart, na.rm = TRUE),  # Get mean time and dev
            mean_deviation = mean(abs(lanePosition)))



# Get Overall means to be plotted
averageAveragesPerPP <- averagesPerPP %>%
  group_by(phoneNrLengthAfterKeyPress, partOfExperiment) %>%  # group by relevant cols
  summarize(dialing_time = mean(mean_time)/1000,                   # Get overall means (mean over pps)
            lateral_deviation = mean(mean_deviation),
            se = (sd(mean_deviation) / sqrt(length(mean_deviation)))
            )                          



# Plot Data using ggplot2
ggplot(data = averageAveragesPerPP,
       mapping = aes(x = dialing_time, 
                     y = lateral_deviation, 
                     colour = partOfExperiment)) +
        geom_point(aes(shape = partOfExperiment), size = 3) +
        geom_line() + 
        geom_errorbar(aes(ymin=lateral_deviation-se,       # Error Bars
                          ymax=lateral_deviation+se), 
                      width = .2) +
        labs(title = "Dialing Time vs Lateral Deviation") + 
        #xlim(0,10) + 
        #ylim(0,1.20) + 
        scale_x_continuous(name="Dialing Time (sec)", 
                           breaks = seq(0,10, 2), limits = c(0,10)) +
        scale_y_continuous(name="Lateral Deviation (m)", 
                           breaks = seq(0,1.2, 0.2), limits = c(0,1.2)) +
        #scale_color_discrete(name = "Part of Experiment", 
         #                    labels = c("Dial Focus", "Steering Focus")) +
        #geom_hline(yintercept= 0.8010104) + # Lane Boundary hoeft niet lol 
        theme_minimal()
        


# TO DO: 

# Check hoe veel punten ik er in moet zetten
# Check of de typingErrorMadeOnTrial == 0 moet zijn
# Misschien door 1000 delen later

```

```{r}
# Section II 
# Gaussian Testing

a <- rnorm(1000, 0.0, 0.13)
hist(a, col = "grey")
# Shape of Histogram is the bell curve
summary(a)
sd(a)
# median = 0.0004640  mean = 0.0001236 sd  = 0.1299274

# low freq: 
b <- rnorm(100, 0.0, .13)
hist(b, col = "grey")
summary(b)
sd(b)
#median = 0.01764 mean =  0.02483 sd = 0.1139517
```

```{r}
tableOfDriftValuesCalibration <- read_csv("tableOfDriftValuesCalibration.csv")
```

```{r}
# Question 2a


tableOfDriftValuesCalibration %>%
  filter(trialTime < 18000, trialTime > 15000) %>%
  group_by(trial) %>%
  ggplot(mapping = aes(
    x = trialTime,
    y = posX,
    group = trial,
    colour = as.factor(trial)
    )) + 
    geom_line(size= 1.3)  + 
    theme_minimal() + 
    guides(col = guide_legend(title = "Trial number",nrow= 10)) + 
    labs(title = "Lateral Position Over Time", x = "Trial Time (ms)", y = "Lateral Position")
  
           
           
   
```

```{r}
#2b
# Create for loop to run code for multiple trials 
# For each trial
# For every 50ms 
# Sample from an rnorm (M = 0, SD = .13)
# == trial
set.seed(300)

sequence = seq(0,3000, by = 50)
trials = seq(1,20)

trialnumber = NULL
pos = NULL
time = NULL

# For loop for simulating trials; using rnorm samples for deviation
for(t in trials){
  for (x in sequence){
    if(x == 0){
      position = 0
      deviation = 0
      position = position + deviation
      trialnumber <- c(trialnumber, t)
      pos <- c(pos, position)
      time <- c(time,x)
      
    }
    else{
      deviation = sample(rnorm(1000,0.0,.013), size = 1)
      position = position + deviation # CUMsum the position points
      trialnumber <- c(trialnumber, t)
      pos <- c(pos, position)
      time <- c(time,x)
    }
  }
}

df <-data.frame(trialnumber, time, pos) # Bind vectors together in a dataframe
df


df %>%
  group_by(trialnumber) %>%
  ggplot(mapping = aes(
    x = time,
    y = pos,
    group = trialnumber,
    colour = as.factor(trialnumber)
    )) + 
    geom_line(size= 1.3)  + 
    theme_minimal() + 
    guides(col = guide_legend(title = "Trial number",nrow= 10)) + 
    labs(title = "Simulated Lateral Position Over Time", x = "Trial Time (ms)", y = "Lateral Position")

```

